// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormStepsController from "./form_steps_controller"
application.register("form-steps", FormStepsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MeetingController from "./meeting_controller"
application.register("meeting", MeetingController)

import MeetingSubscriptionController from "./meeting_subscription_controller"
application.register("meeting-subscription", MeetingSubscriptionController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ProgressBarController from "./progress_bar_controller"
application.register("progress-bar", ProgressBarController)

import ReadmoreController from "./readmore_controller"
application.register("readmore", ReadmoreController)

import RecordingController from "./recording_controller"
application.register("recording", RecordingController)

import SearchUsersController from "./search_users_controller"
application.register("search-users", SearchUsersController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)

import Chart from 'stimulus-chartjs'
application.register('chart', Chart)
